### ISSUE TITLE
model predicts blank for every test sample

### ISSUE THREAD

**Issue by sruteesh** [reith/deepspeech-playground#1]
Hello,
I tried testing the model `45-best-val-weights.h5` but was consistently getting blank outputs. 
I tried testing with my own samples aswell as librispeech samples, but no change in result.
I am using the `models-evaluation.ipynb` notebook mentioned. No changes to the notebook except for the path inputs.
I am using it using latest `Keras 2.0.8` and `TF 1.3.0`
Can u look into the matter.
Thanks

**Comment by reith** [comment]
Data normalization was needed: `datagen.reload_norm('860-1000')`
