### ISSUE TITLE
Want to train DeepSpeech for Indian English

### ISSUE THREAD

**Issue by gulatig-zz** [reith/deepspeech-playground#10]
Hi Reith,

Currently we are using a pre-trained DeepSpeech model for our project, we need to train the model for indian english, can I have some pointers or suggestions from you.

Regards,
Gaurav

**Comment by reith** [comment]
Maybe more RNNs and just training those RNNs helps.  It really has nothing to do with this project as it tries to train by two different output.  I guessed the way I proceed to train, (i.e. training specific layers in each step) helped to converge faster.  Maybe you can try use same method to apply transfer learning on your pre-trained model.

**Comment by shaikhalid** [comment]
> Hi Reith,
> 
> Currently we are using a pre-trained DeepSpeech model for our project, we need to train the model for indian english, can I have some pointers or suggestions from you.
> 
> Regards,
> Gaurav

have you trained any model on indian english???
