### ISSUE TITLE
No module named 'ctc'

### ISSUE THREAD

**Issue by hatemZamzam** [reith/deepspeech-playground#11]
In the model.py file, you imported ctc but it's not found inside the repo !!

**Comment by hatemZamzam** [comment]
It's working with keras_backend="theano" (y)
but with tensorflow it's not working.

**Comment by reith** [comment]
Follow main repo (https://github.com/baidu-research/ba-dls-deepspeech) readme for warp-ctc.

**Comment by hatemZamzam** [comment]
Yeah thank you, I followed the steps, but I think ctc doesn't work on windows right ?
it raises an exception of unsupported platform.

**Comment by reith** [comment]
I don't know. Did you check ctc c libry docs?
