### ISSUE TITLE
How to integrate/use this with tensorflow model ?

### ISSUE THREAD

**Issue by CR1AT0RS** [reith/deepspeech-playground#3]
Hi I am trying to see how much improvement I get after combining this with deepspeech generated model. Do you have any ideas how to integrate these two ?

**Comment by reith** [comment]
How much your trained model is good?

I couldn't get CER down to %10 using Baidu's codes and my limited resources but I reached to %5 with this phoneme method. You might not get any improvement if you already have a good model..

**Comment by MuruganR96** [comment]
Sir I have my own trained model. but it is working for that particular trained audios only. how to combine deepspeech pretrained language model, else other common voice model. sir help me. i am very low knowledge about this topic. thank you sir.
