### ISSUE TITLE
input shape for inference with new data

### ISSUE THREAD

**Issue by Drea1989** [reith/deepspeech-playground#4]
hello,first thank you for sharing your code, i tried to export the model to run inference and i would like to get some clarification on the input data shape, if i try to send an audio file (wav, 1 channel at 16khz) i get this error:
```
INVALID_ARGUMENT, details="input must be 4-dimensional[102400,1]
	 [[Node: conv_1d_1/convolution/Conv2D = Conv2D[T=DT_FLOAT, _output_shapes=[[?,1,?,1000]], data_format="NHWC", padding="VALID", strides=[1, 1, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv_1d_1/convolution/ExpandDims, conv_1d_1/convolution/ExpandDims_1)]]")
```
thank you for your help

**Comment by reith** [comment]
Hi, input of deepspeech model is spectrogram not raw wave data. If you are
using accompanying scripts (train.py) it's done for you otherwise you
should [make spectrograms](https://github.com/reith/deepspeech-playground/blob/master/utils.py#L117)
and pass it to model.

**Comment by Drea1989** [comment]
i am experimenting using tensorflow serving, i have added the functions spectrogram and spectrogram_from_file to the preprocessing steps. however i am getting this output, shape: (231, 161) dtype: float64 this causes this error: 
INVALID_ARGUMENT, details="Expects arg[0] to be float but double is provided")
am i missing any steps?
thanks

**Comment by reith** [comment]
Unfortunately I'm not aware of serving.. Judging by error I guess it needs
type hints for preprocessor functions..
