### ISSUE TITLE
'860-1000' dataset?

### ISSUE THREAD

**Issue by chuckcho** [reith/deepspeech-playground#8]
I found this repo very useful, and appreciated your effort on this! :)
Was wondering what "860-1000" dataset meant in your `data_generator.py` -- looked like a subset of librispeech dataset used for extracting mean/std. Do you have a sense if this mean/std can be applied to speech data from other domain or dataset?

**Comment by reith** [comment]
Yes, It's 1000 random samples of LibriSpeech train-500 and train-360 datasets combined.
I don't think it can help much.. I tried different samples for normalization and always after a little training, model would rich to almost certain quality, no matter of how much samples were large or small.

**Comment by chuckcho** [comment]
@reith that makes sense. many thanks for clarification!
