### ISSUE TITLE
How to combine my own custom model and pretrained deepspeech language model

### ISSUE THREAD

**Issue by MuruganR96** [reith/deepspeech-playground#9]
Sir I have my own trained model. but it is working for that particular trained audios only. how to combine deepspeech pretrained language model, else other common voice model. sir help me. i am very low knowledge about this topic. thank you sir.

**Comment by reith** [comment]
This model does not include/train a language model. There is a naive approach to use a pretrained language model in [evaluation notebook](https://github.com/reith/deepspeech-playground/blob/master/models-evaluation.ipynb) and you can get idea in `best_lm_alternative`. I didn't get whether your model is based on Baidu's DeepSpeech or mine. If you strongly want to use a language model, you should take a look to [Mozilla's DeepSpeech](https://github.com/mozilla/DeepSpeech).
